//
//  currentUser.swift
//
//  File Generated by macintoshhd on 07/09/2020.
//  Using model_gen.py
//

struct CurrentUser: Decodable {

	var accountExpired: Bool
	var name: String
	var hasNewTerms: Bool
	var enabled: Bool
	var passwordExpired: Bool
	var accountLocked: Bool
	var dateCreated: String
	var signupCredentialEmailSent: Bool
	var notificationsEnabled: Bool
	var lastUpdated: String
	var termsAndConditionsAccepted: Bool
	var id: String
	var signupEmailSent: Bool
	var finerioCode: String
	var customerId: Int
	var type: String
	var email: String
	var signupFrom: String
	var signupCredentialPushSent: Bool

}

