//
//  Movements.swift
//
//  File Generated by macintoshhd on 07/09/2020.
//  Using model_gen.py
//

struct Movements: Decodable {

	var data: [MovementsData]
	var size: Int

}

struct MovementsData: Decodable {

	var account: MovementsAccount
	var description: String
	var deleted: Bool
	var type: String
	var lastUpdated: String
	var customDate: String
	var amount: Float
	var customDescription: String
	var concepts: [MovementsConcepts]
	var date: String
	var inResume: Bool
	var dateCreated: String
	var balance: Float
	var hasConcepts: Bool
	var id: String
	var duplicated: Bool

}

struct MovementsAccount: Decodable {

	var name: String
	var institution: MovementsInstitution
	var deleted: Bool
	var number: String
	var lastUpdated: String
	var dateCreated: String
	var availableBalance: Float
	var user: MovementsUser
	var balance: Float
	var type: String
	var id: String

}

struct MovementsConcepts: Decodable {

	var category: MovementsCategory
	var description: String
	var amount: Float
	var type: String
	var id: String
	var movement: String?

}

struct MovementsInstitution: Decodable {

	var status: String
	var code: String
	var id: Int
	var name: String

}

struct MovementsUser: Decodable {

	var id: String

}

struct MovementsCategory: Decodable {

	var color: String
	var textColor: String
	var id: String
	var parent: MovementsParent
	var name: String

}

struct MovementsParent: Decodable {

	var id: String

}

